### ISSUE TITLE
[Feature] Alchemical bombs and similar weapons should be excluded from activations

### ISSUE THREAD

**Issue by maplealmond** [ChasarooniZ/pf2e-item-activations#11]
**Is your feature request related to a problem? Please describe.**
The alchemical bombs already show up as weapons. Having them appear as activations is duplicate clutter.

**Describe the solution you'd like**
Items which are weapons (e.g. acid flask or junk bomb) should not add activations.

**Describe alternatives you've considered**
Deleting unwanted activations is not too burdensome for most cases but a bomber alchemist will be adding items every game day.

**Comment by ChasarooniZ** [comment]
Ah didn't know those were being added, will remove on latest update

**Comment by ChasarooniZ** [comment]
Fixed as of `11.2.2`
