### ISSUE TITLE
[Feature/Bug] Do not include unidentified items adding activations

### ISSUE THREAD

**Issue by Pyroman2xxx** [ChasarooniZ/pf2e-item-activations#14]
**Is your feature request related to a problem? Please describe.**
Currently activations are added for unidentified items that are added to a PC's sheet. This gives away information to the player that they should not have.

**Describe the solution you'd like**
Not include unidentified item activations.

**Comment by ChasarooniZ** [comment]
it does? That's weird, my intention when making it was for it not to do that, I'll double check

**Comment by Pyroman2xxx** [comment]
Thank you for your work on this mod!

I did not do extensive testing but the main item that it happened with is one of my players is carrying 'The Whispering Reeds' book from the Abomination Vaults AP. It is adding two activatable abilities.

**Comment by ChasarooniZ** [comment]
Hmm okay, I'll look into it
