### ISSUE TITLE
Keyword expansion [Feature] 

### ISSUE THREAD

**Issue by TaleSale** [ChasarooniZ/pf2e-item-activations#8]
Hello. I'm impressed with the 11.1.0 update.

But I would like to ask you to expand the search keyword register to create activations. Please add search by:

- \<span class="pf2-icon"> since not everywhere the description switched to \<span class="action-glyph">
- I also noticed that your action counter is only by numbers, but in the descriptions there are also action counters by letters, for example \<span class="pf2-icon">f\</span> or \<span class="action-glyph">f\</span> is the same as \<span class="action-glyph">4\</span>
- And the most important thing is that I play in the Russian translation and in your translation the word **Activate** is translated as **Активация**

If you make these changes, your module will work in Russian translation. Thank you very much!

**Comment by ChasarooniZ** [comment]
Putting this higher on my hierarchy, changes don't look to be too much to do relatively easily
